package net.galgan.skyupextras;

import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.text.Text;

import java.util.Set;

public class QuestData {

    public static final Set<String> containerTitles = Set.of(
            "\uE003\uE150\uE002Wyzwania",
            "\uE001\uE151\uE002Wyzwania » Nowicjusz",
            "\uE001\uE152\uE002Wyzwania » Wtajemniczony",
            "\uE001\uE153\uE002Wyzwania » Zaawansowany",
            "\uE001\uE154\uE002Wyzwania » Znawca",
            "\uE001\uE155\uE002Wyzwania » Ekspert",
            "\uE001\uE156\uE002Wyzwania » Mistrz",
            "\uE001\uE157\uE002Wyzwania » Guru",
            "\uE001\uE158\uE002Wyzwania » Legenda",
            "\uE001\uE159\uE002Wyzwania » Wirtuoz",
            "\uE001\uE15A\uE002Wyzwania » Bonus"
    );

    public static final Set<String> questNames = Set.of(
            "» Od czego zacząć? «",
            "» Podstawowy kamieniołom «",
            "» Obozowisko «",
            "» Cieśla amator «",
            "» Jabłecznik «",
            "» Składzik «",
            "» Ściernisko «",
            "» Mała farma «",
            "» Piekarz «",
            "» (Nie)zbilansowana dieta «",
            "» Kucharz grzybowy «",
            "» Plantacja «",
            "» Zielony Jeż «",
            "» Moczykij «",
            "» Huta «",
            "» Gotowy do Pracy «",
            "» Światełko nadziei «",
            "» Szerokie horyzonty «",
            "» Moja pierwsza praca «",
            "» Ciasno, ale własno «",
            "» Kamienny kilof «",
            "» Mało miejsca dla kolegów «",
            "» Tajga «",
            "» Gospodarka leśna «",
            "» Drwal alchemik «",
            "» Zmory podziemi «",
            "» Kryptomaniak «",
            "» Zbrojownia «",
            "» Kuźnia «",
            "» Architekt wnętrz «",
            "» Żabie oświecenie «",
            "» Szamaństwo «",
            "» Ranczo «",
            "» Pożywne śniadanie «",
            "» Sok z buraka «",
            "» Rybak «",
            "» Przelewa się «",
            "» Piecoznawstwo «",
            "» Morski świat do morskich opowieści «",
            "» Agresywna ekspansja «",
            "» Pracuś «",
            "» Wiśniowe bagna «",
            "» Wioska smerfów «",
            "» Szlambonurek «",
            "» Przymiarki do dyniarki «",
            "» Frytki do tego? «",
            "» Cukiernik «",
            "» Rzeźnik «",
            "» Polowanie na króliki «",
            "» Ogromna jajecznica «",
            "» Ryba chwyciła haczyk «",
            "» Pokaz fajerwerków «",
            "» Jacuzzi «",
            "» Mój bohater «",
            "» Obieżyświat «",
            "» Łucznictwo «",
            "» Kolekcjoner sztuki «",
            "» Biednemu wiatr w oczy «",
            "» Przemiana «",
            "» Dzwoń na trwogę «",
            "» Da się żyć «",
            "» Piekło «",
            "» Piekielny kamień «",
            "» Łowca «",
            "» Zapasowe ciało «",
            "» Znawca walki na dystans «",
            "» Kryptolog «",
            "» Archeolog «",
            "» Daleko jeszcze? «",
            "» Witamy w endzie «",
            "» Jaki skyblock, taki smok «",
            "» Willy Wonka «",
            "» Owocowy las «",
            "» Super odporność «",
            "» Leśny zakątek «",
            "» \"Potężna wichura łamiąc duże drzewa...\" «",
            "» Agrotechnika «",
            "» Susza «",
            "» Szkarłatne rzeczy «",
            "» Nie igraj z ogniem «",
            "» Skumulowana Energia «",
            "» Ochłodzenie klimatu «",
            "» Magia «",
            "» Dobry pasterz «",
            "» Niebieski kwiat i kolce «",
            "» Handlarz z piekła rodem «",
            "» Pracownik miesiąca «",
            "» Własny dinozaur «",
            "» Szkółka leśna «",
            "» Czas na las «",
            "» Sięgając korzeni «",
            "» Jagodzianka «",
            "» Szczęściarz «",
            "» Pancerna hodowla «",
            "» Grabarz? Garbarz! «",
            "» Słoneczny patrol «",
            "» Pasieka «",
            "» Magazyn «",
            "» W zwolnionym tempie  «",
            "» Piekielny szaleniec «",
            "» Obce organizmy «",
            "» Nemezis «",
            "» Mur «",
            "» Mój słodziutki «",
            "» Purée «",
            "» Dziki Zachód «",
            "» Basen olimpijski «",
            "» Podwodne życie «",
            "» Mamut morski «",
            "» Epoka diamentów «",
            "» Boska ręka «",
            "» Królowa sawanny «",
            "» Skarbek «",
            "» Piekielny kowal «",
            "» Zaklęty kowal «",
            "» Magazynier «",
            "» Redstonowiec «",
            "» Rolnik z zaświatów «",
            "» Gorzka (wątpliwa) przyjemność «",
            "» Pola malowane zbożem rozmaitem «",
            "» Sukulenty «",
            "» Artysta kulinarny «",
            "» Raz kozie śmierć «",
            "» Podpłomyk «",
            "» Pokój alchemika «",
            "» Nekromanta «",
            "» Arachnofobia «",
            "» Glazurnik «",
            "» Antofobia «",
            "» Rafa koralowa «",
            "» Zero absolutne «",
            "» To moje bagno! «",
            "» Skondensowana wiedza «",
            "» Chów ściółkowy «",
            "» Kierownik roku «",
            "» Uczeń czarnoksiężnika «",
            "» Próba testu «",
            "» Prosto z kopalni «",
            "» Kolekcjoner klejnotów «",
            "» Ametyściara «",
            "» Siekieronator «",
            "» Ziemianin «",
            "» Szatańskie łzy «",
            "» Piekielna twierdza «",
            "» Stawik kałamarnic «",
            "» Królicza opatrzność «",
            "» Kuter rybacki «",
            "» Co za dużo to niezdrowo «",
            "» Dyniara, czy nie dyniara? «",
            "» Ziemniaczki zostaw «",
            "» Kresowe owocki «",
            "» Nieudolny rolnik «",
            "» Bezpieczeństwo Hamuje Prace «",
            "» Gdy zapada noc «",
            "» Świński makler «",
            "» Degustator «",
            "» Mój mały świat «",
            "» Skołatane nerwy «",
            "» Cesarz rybołówstwa «",
            "» Pszczelarz «",
            "» Ostatni przyjaciele «",
            "» Nawiedzony tropiciel «",
            "» Świecznik «",
            "» Shulkusiowa rodzina «",
            "» Piroman absolutny «",
            "» Miodowe Lata «",
            "» Kolorowa plaża «",
            "» Geolog «",
            "» Biblioteka Aleksandryjska «",
            "» Prastare zwoje «",
            "» Piekielny rycerz «",
            "» Czarny pas w dungeonie «",
            "» CEO «",
            "» Władca skyblocka «",
            "» Wirtuoz piekła «",
            "» Leśny potwór «",
            "» Warzywniak «",
            "» Piekielna roślinność «",
            "» Bambusowy las «",
            "» Czekoladowe fondue «",
            "» Trzcinator «",
            "» Operacja Borówka «",
            "» Obrońca wszechświata «",
            "» Wielka uczta «",
            "» Sztygar «",
            "» Władca pustki «",
            "» Budowniczy na medal «",
            "» Gorączka ametystu «",
            "» Ofiara dla Dadźboga «",
            "» Maszynka do mielenia «",
            "» Pracoholik «",
            "» Technik «",
            "» Złoto w każdej postaci «",
            "» Wspinaczka «",
            "» Świat pełen kolorów «",
            "» Robi się gorąco «",
            "» Strażnik światłości «",
            "» Puk puk, kto tam? «",
            "» Prawiebloki «",
            "» Świat jest piękny «",
            "» Nieszczęśliwy traf «",
            "» Obłąkany rolnik «",
            "» Kolumbijscy drapieżcy «",
            "» Epoka lodowcowa «",
            "» Czarno to widze «",
            "» Pan życia i śmierci «",
            "» Nic mnie już nie zaskoczy «",
            "» Imiennik «",
            "» Zadanie codzienne «"
    );

    public static final String completedLore = "LoreComponent[lines=[empty, empty[siblings=[literal{▪ }[style={color=dark_gray,bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{Zadanie ukończone!}[style={color=green,!bold,!italic}]]], empty], styledLines=[empty[style={color=dark_purple,italic}], empty[style={color=dark_purple,italic}, siblings=[literal{▪ }[style={color=dark_gray,bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{Zadanie ukończone!}[style={color=green,!bold,!italic}]]], empty[style={color=dark_purple,italic}]]]";

    public static final Text questSelectedPrefix = Text.empty()
            .append(Text.literal("Sky").styled(s -> s.withColor(0x00FFFF).withBold(true)))
            .append(Text.literal("UP").styled(s -> s.withColor(0xFFFFFF).withBold(true)))
            .append(Text.literal("+").styled(s -> s.withColor(0xFFFF55).withBold(true)))
            .append(Text.literal(" ").styled(s -> s.withColor(0xFFD700).withBold(true)))
            .append(Text.literal("» ").styled(s -> s.withColor(0x555555).withBold(true)))
            .append(Text.literal("Wybrano zadanie: ").styled(s -> s.withColor(0x00AAAA)));
}
